# Abstract

Early-career educators face numerous challenges during their transition from educator preparation programs into professional employment contexts (i.e., their induction period), and they seek support from a variety of sources. The teacher induction literature has reported a "two worlds pitfall" caused by conflicting messages about what and how to teach from the academic world of the preparation program and the practical world of the teaching classroom. Further complicating teacher induction is the new reality that early-career educators are no longer seeking help with their profession from just two worlds, but a universe of many worlds accessible through social media—an edu-verse. In this study, I will interview early-career educators about from whom they seek support during induction and how they use social media for this, if at all. From qualitative thematic analysis of the interviews, I will develop and administer a quantitative survey to see how common these induction experiences are. Because much is still unknown in this area, findings from my this study should benefit early-career educators as well as their teacher educators and mentors.

## Keywords

early-career educators, induction, social media, professional learning networks
