# Introduction

Early-career educators (ECEs) face numerous challenges during their transition from educator preparation programs into professional employment contexts (i.e., their *induction* period). ECEs seek support from a variety of sources during this time. The teacher induction literature has reported a “two worlds pitfall” (Feiman-Nemser & Buchmann, 1985) caused by conflicting messages from the academic world of the preparation program and the practical world of the professional teaching context. ECEs enter their school of employment with notions of teaching that are not shared  &mdash; or in some instances, are even actively discouraged  &mdash; by more experienced colleagues and administrators in that school setting. ECEs must then try to navigate and reconcile conflicting messages to decide how they will enact educational practice. Often, contextual pressure to adapt to the employment environment means that worthwhile academic notions of education from preparation programs are abandoned by ECEs (Feiman-Nemser & Buchmann, 1985).

Further complicating teacher induction is the new reality that ECEs are no longer seeking help with their profession from just two worlds. Through *social media*—a set of participatory practices for using media socially and publicly (Humphreys, 2016)  &mdash; educators’ traditional two worlds have expanded to a universe of many worlds  &mdash; an *edu-verse*. Thus, ECEs may have to navigate conflicting messages about what and how to teach from their preparation program, local employment context, and social media platforms. However, research on educators’ use of social media has rarely focused on the particular challenges experienced by and needs of ECEs.

The purpose of this study is to explore what supports for professional learning ECEs seek during induction, if any; from whom; and how, if at all, they use social media with the intention of seeking supports and connections. This research purpose fills a gap between the induction literature, which does not fully consider recent technological advancements, and the social media literature, which does not take into account the needs of new educators. It is likely that ECEs are seeking supports for induction needs from far more sources today than have been previously studied  &mdash; supports from and through social media should be specifically considered. In addition, the intense professional and personal dissonance that comes with moving from *learning about* teaching to *actually practicing* teaching suggests the challenges and needs of ECEs are likely far more complicated than have been accounted for by research on educators’ uses of social media generally. From a practical perspective, it is important to explore and understand this gap because ECEs are already experiencing and navigating a new professional reality  &mdash; a rapidly expanding edu-verse created by the current social media landscape.
