# Framework

This study is framed by a *professional learning network* (PLN) lens. Trust (2012) defined a PLN as “a system of interpersonal connections and resources that support informal learning” (p. 133). A PLN lens is well-suited to frame this study because it focuses on educators’ professional learning while expanding the scope of interpersonal connections to account for global reach through the Internet without discounting local, offline relationships. For instance, respondents in Trust, Krutka, and Carpenter’s (2016) survey study described the scope of their PLNs in various ways, including solely in terms of face-to-face (i.e., offline) components, solely in terms of online components, and in terms of both face-to-face and online (i.e., blended) components.

In addition, although Trust’s (2012) definition highlighted the benefit of PLNs for informal learning, other studies have acknowledged that PLNs include elements of traditional professional development while also extend beyond these formal learning environments (Krutka, Carpenter, & Trust, 2017; Prestridge, 2019). For instance, Kim, Frank, and Spillane (2018) described how schools are composed of both a formal organization (i.e., defined teacher positions and roles) as well as informal networks (i.e., who students turn to for expertise). It may be the case that ECEs experience a similar mix of formal and informal induction supports in the local school context, incorporating both officially assigned mentors as well as relationships that more organically emerge as supports. The inclusion of social media then further expands ECEs’ opportunities for informal mentoring and access to expertise, in addition to elements of formal learning (Greenhow & Lewin, 2016). In sum, PLNs often incorporate a mix of both formal and informal elements spanning both local and global contexts.

The scope of a PLN lens &mdash; including both face-to-face and online as well as formal and informal elements &mdash; has the potential to address the gap between research on teacher induction and research on educators’ use of social media. In terms of makeup, PLNs are *interpersonal connections* (i.e., people and groups), and between these people and groups are being passed *supports for professional learning* &mdash; what Trust (2012) termed “resources” but could include knowledge, skills, curricular materials, and encouragement in addition to general resources. Finally, the emphasis of a PLN on professional learning may suggest that there are some underlying reasons *why* educators are seeking interpersonal connections and supports. These underlying reasons may imply a deficit in professional development elsewhere (e.g., district workshops focused on general teaching practices rather than the specific nuances needed for teaching a particular subject) or a heightened need among new educators for just-in-time support as they continue to learn to teach (e.g., how to lead an inquiry-based lesson tomorrow on a specific computer-science principle or skill). PLNs are reminiscent of Packard’s (2003) earlier *composite mentoring* concept, defined as “the strategic selection of a diverse set of mentors, each mentor offering one aspect of the desired mentoring experience” (p. 337). For novices who are unable to find one mentor who embodies all that they wish to become, composite mentoring allows them to take an active role in finding their desired mentoring experiences (Packard, 2003). PLNs further broaden the scope from mentoring to more general professional learning; both models assume that novices are taking a constructivist posture in their own development. Flanigan (2011) encapsulated these ideas by characterizing PLNs as grassroots movements initiated by educators.
