# Purpose and Research Questions

The purpose of this study is to explore what supports for professional learning ECEs seek during induction, if any; from whom; and how, if at all, they use social media with the intention of seeking supports and connections. In other words, this study seeks to understand if and how ECEs navigate the edu-verse, looking for support in response to challenges experienced during induction. A PLN framing of this purpose suggests considering *what* ECEs are looking for and *why*, as well as *who* ECEs connect to &mdash; both locally and through social media. Thus, I will accomplish the research purpose by answering four research questions:

- **RQ1.** What supports for professional learning, if any, are ECEs seeking during induction?
- **RQ2.** What reasons, if any, do ECEs report for seeking induction supports, and what reasons do they give, if any, for not seeking induction supports?
- **RQ3.** What interpersonal connections do ECEs make when seeking supports for professional learning during induction?
- **RQ4.** How, if at all, do ECEs use social media as a modality to access supports for professional learning during induction?

I will answer these research questions by asking ECEs about their induction experiences. First, I will interview ECEs to inductively establish themes related to my four research questions. From qualitative thematic analysis of the interviews, I will develop and administer a quantitative survey to see how widespread these induction experiences are among ECEs. Through this process, I will contribute to filling the gap in the literature by purposefully exploring both social media use and the specific experiences of ECEs.

