# Anticipated Findings

The purpose of this study is to explore what supports for professional learning ECEs seek during induction, if any; from whom; and how, if at all, they use social media with the intention of seeking supports and connections. Although I do not know exactly what I will find as a result of this study, I have several hypotheses, which I describe in the following paragraphs.

## RQ1: Induction Supports for Professional Learning

I expect that some common themes will emerge from the qualitative interviews regarding the types of induction supports for professional learning ECEs are looking for. These themes may include help with time management, classroom management, relating to students, and content expertise (subject-matter questions), as well as a felt need for emotional encouragement. I do not have a prediction for how generalizable these themes will be to the larger sample in the quantitative survey stage.

## RQ2: Reasons for Seeking Induction Supports and Reasons for Not Seeking Supports

It may be the case that ECEs have difficulty reporting their needs, but they may still be able to identify things that are not working. If this is true, then I might expect ECEs to describe frustrations with district-mandated professional development sessions that are too general to be useful and end up feeling like a waste of time. I expect ECEs to report seeking induction supports in response to a specific felt need that prompts them to search for help or an answer. However, because of frustrating prior experiences with inductions supports, I anticipate some ECEs to report *not* seeking induction supports. In addition, some ECEs may choose not to access induction supports through the modality of social media because they feel that their circumstance would be too specific for outsiders to understand and offer meaningful support. For instance, an ECE in a high-poverty school may feel that a stranger outside this context would not be able to understand their situation enough to offer meaningful support.

## RQ3: Interpersonal Connections for Induction Supports

I expect that ECEs will report connecting with a variety of individuals and groups in search of induction supports. Individuals may include instructors and classmates from their preparation programs; peers, mentors, and administrators in their school of employment; and friends, colleagues, and edu-celebrities on social media. Groups may include cohorts from the preparation program or school of employment, structured online learning communities like the PLNs facilitated by the International Society for Technology in Education (ISTE, n.d.), as well as more informal gatherings and conversations such as education-related Twitter hashtags, Pinterest boards, or even the personal school-external networks described by März and Kelchtermans (2020).

## RQ4: Use of Social Media as a Modality to Access Induction Supports

I expect that there will be parallels between the kinds of experiences that ECEs have with social media-mediated induction supports and their offline, face-to-face ones. That is, I expect that ECEs will seek many of the same supports on social media as they do offline, for many of the same reasons, and from similar types of interpersonal connections. However, I do expect there to be differences, particularly in terms of the reasons why they seek induction supports or not. I expect that ECEs will report using social media to find induction supports because of the ease of use, time efficiency, and just-in-time support that is essential to ECEs who are still figuring out on a day-to-day basis what their needs are. I expect themes to emerge related to a cost-benefit analysis (whether conscious or unconscious) of whether social media are worth the time, distractions, overwhelming number of connections and resources, and sense of doing extra work outside school hours. The reasons why ECEs choose not to seek induction supports may be exacerbated by the social media modality. That is, if an ECE felt like someone outside their high-poverty school would not understand their context and be able to offer meaningful support, this feeling may be even stronger when considering whether an unknown person on social media elsewhere in the world would have something to offer.

This study presents an opportunity to ask interview participants and survey respondents which social media platforms they use to seek connections for induction support. I expect some ECEs to describe using a variety of social media platforms to look for help, such as Instagram, Pinterest, TeachersPayTeachers, Twitter, Facebook groups, and Reddit. Of course, ECEs are also likely to turn to offline supports as well &mdash; even self-initiated ones &mdash; such as colleagues in their school building, and some may even ask their students for feedback. Still, I expect that ECEs will be seeking support not just from their preparation program or their current professional context, but from the edu-verse, the multitude of resources and connections available through social media. The findings from this study will help create an updated map of the extent of the edu-verse as well as how often ECEs use different platforms.

I expect that the participation inequality that has been well-documented in online and social media communities (e.g., Nielson, 2006; Staudt Willet, 2019) will be evident in the survey results &mdash; a small number of respondents will use social media frequently to make connections related to their induction needs, whereas a large majority of respondents will use social media infrequently and some not at all for this purpose. In addition, even amongst those who use social media frequently, the manner of use will vary. I expect that most of the frequent users will be in the “lurker” &mdash; or, in a less negative connotation, “observer” (Edelmann, 2013) &mdash; category, which Prestridge (2019) termed “info-consumer.” This result would be welcome, as it would illustrate a benefit of my mixed method approach: by interviewing and surveying ECEs, I can collect rich data from those who choose to contribute little to no content to social media but are participants nonetheless. This is a distinct advantage over the data-mining, “digital traces” methods of my past research (e.g., Staudt Willet, 2019; Staudt Willet & Carpenter, 2019), where data collection is limited to observable behaviors and content. In this study, I will be able to gather thought processes and emotions, regardless of whether content is shared. 

I expect that ECEs’ experiences and interpretations will vary; some will love everything about the interpersonal connections they have made on social media, and others will describe social media as confusing and overwhelming. If this hypothesis holds, these findings would be an interesting contrast to the bulk of research in educational technology that seems to present social media affordances as overwhelmingly positive. In this study, I do not expect ECEs to report such a positive perception of their own social media participation.
