# Significance

## Implications for Practice

Results from this study should offer practical implications for ECEs, teacher educators, and teacher mentors. ECEs may benefit from reading about how their peers have sought support during induction &mdash; or why they have chosen not to &mdash; and whether social media (and which platforms) seemed to aid accessing supports and making interpersonal connections. If a number of ECEs have found certain social media platforms to be beneficial and others to be problematic, then their peers could determine which practices to engage in or avoid. Teacher educators and mentors may benefit from knowing what current offerings of induction supports feel unhelpful to ECEs as well as what kinds of informal professional learning practices feel worthwhile. This would enable teacher educators and mentors to complement their formal efforts in supporting ECEs with additional options for induction support through social media, as well as an understanding of when to offer appropriate caution to ECEs seeking their own self-initiated solutions.

This study has timely and practical significance because there continue to be high rates of attrition and turnover among ECEs, with high costs to students, schools, and districts. Induction challenges have real effects on ECEs, who feel like they are in survival mode (Thompson et al., 2013; Zhukova, 2018), left to “sink or swim” in the isolation of their own classrooms and educational contexts (Ingersoll, 2012). In recent years, teachers have been leaving the classroom at an unprecedented rate (Carver-Thomas & Darling-Hammond, 2017; Hackman & Morath, 2018; Hargreaves & Fullan, 2012), with especially high attrition among ECEs (Ronfeldt & McQueen, 2017). The cost of teacher attrition impacts numerous parties. School districts pay a price &mdash; for instance, more than $20,000 to replace each teacher who leaves an urban school district (Carver-Thomas & Darling-Hammond, 2017). More importantly, educator turnover can negatively affect students, reducing learner achievement (Carver-Thomas & Darling-Hammond, 2017; Ronfeldt, Loeb, & Wyckoff, 2013). The departing educators themselves find themselves in the midst of a confluence of factors that lead to departure; Dunn’s (2018) study of publicly-shared resignation letters revealed that educators left the profession with intense emotion and regret, but nonetheless still committed to the needs of students. Clandinin et al. (2015) concluded that efforts should focus on questions of *sustaining* educators rather than questions of *retaining* them &mdash; which means attending to the lives of ECEs and not just identifying factors that cause attrition.

Educator preparation programs, formal induction programs, and teacher professional development have not yet solved these problems, and research on educators’ uses of social media have not yet even considered these issues. The possibilities afforded by social media seem to be a promising solution, but it may also be the case that the increased connectivity afforded by social media creates new problems for ECEs even while alleviating others. Putnam and Borko (2000) argued that although new kinds of learning communities may offer opportunities for improving educational practice, these opportunities may also usher in new tensions. Horn, Nolen, Ward, and Campbell (2008) warned there are both potential benefits and problems resulting from the tension that arises from navigating between the traditionally conceived two worlds of the educator preparation program and the professional teaching context. On one hand, conflicting messages help novices develop their pedagogical reasoning and ability to adapt and contextualize; on the other hand, if there is too much difficulty, the theory of the preparation program is often abandoned in favor of the practices of new colleagues (Feiman-Nemser & Buchmann, 1985; Horn et al., 2008). In addition, if the two worlds notion is expanded to an edu-verse to take into consideration how ECEs might seek support through social media, new tensions may be introduced in addition to the benefits. For instance, it is likely that ECEs will have difficulty determining the quality of resources found through social media and contextualizing resources that were sourced globally (Jones & Preece, 2006). Additionally, some ECEs may choose not to avail themselves any induction supports, with particularly strong feelings toward supports accessed through social media.

 In sum, this study will contribute new understanding to the convergence of tensions that may be felt by ECEs as they consider whether or not to seek induction supports, including whether or not to look for help on social media. This contribution will have implications for following Clandinin et al.’s (2015) recommendation to seek to *sustain* ECEs by attending to their lived experiences, not just aim to *retain* them.

## Implications for Research

Ingersoll and Strong (2011) argued that future research on teacher induction needs to be rooted in theory and be critical; future studies must go beyond whether or not an induction support works and should also answer why. The exploratory sequential mixed methods design of this study will help deepen understanding of induction supports. This design is appropriate for creating an initial understanding of a phenomenon of interest, as would be the case for filling the gap between research on teacher induction and research on educators’ use of social media. This study’s design will allow ECEs to report what supports for professional learning they are seeking during induction, if any; underlying reasons why; what individuals and groups they are connecting to; and how, if at all, they use social media toward this end. This study’s purpose and research questions represent a structured application of the PLN framework, using this concept as a lens to prompt questions of what, why, who, and how (if at all) with social media. Other researchers should find the PLN framework and these subsequent research questions to be useful for exploring additional questions about how educators of all experience levels seek professional learning.

The findings from this study &mdash; both the qualitative and quantitative results &mdash; should also suggest a number of various directions for future research. For example, the results will provide research questions for a study implementing data-mining methods &mdash; the emergent themes will suggest which digital traces to look for and how to analyze them. An additional contribution of this work to educational research is the survey instrument itself, inductively developed from qualitative data collected from actual ECEs. The survey instrument could be used by future researchers for more targeted studies of new educators &mdash; defining cases, for instance, by geography, gender, or ethnicity.

In addition, although inferential statistics are beyond the scope of the proposed study, an immediate follow up study could develop multi-level models to determine variance within and between the demographic categories recorded by the survey. In other words, this inferential approach would measure potential effects of: (a) years of teaching experience, (b) grade level taught, (c) content area taught, (d) type of school (urban, suburban, rural), (e) zip code, (f) type of educator preparation (i.e., undergraduate, graduate, alternative certification, none), (g) ethnicity (Asian, Black/African, Causasian, Hispanic/Latinx, Middle Eastern, Native American, Pacific Islander, prefer to self-describe , prefer not to answer), and (h) gender (female, male, non-binary/third gender, prefer to self-describe, prefer not to answer). Finally, because of this study’s specific research purpose, I will collect information related to social media use: (i) social media platforms used, (j) length of time active on social media, (k) frequency of social media use (daily, several time a week, several times a month, rarely), and (l) professional purposes for social media use (following news and trends in education, seeking and giving emotional support related to job, finding and sharing educational resources and curricular materials, collaborating with colleagues in education, other).
